"use client";

import Navbar from "@/components/Navbar";
import "./globals.css";
import { Inter } from "next/font/google";
import Footer from "@/components/Footer";
import Script from "next/script";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  icons:{
    icon:"./logodigital.png"
  },
  title: "Digital Soul",
  description: "Generated by next.js",
};

const initBotpress = () =>{
  window.botpressWebChat.init({
    "composerPlaceholder": "escreva aqui",
    "botConversationDescription": "o melhor chatbot de Portugal",
    "botId": "14ea4229-d163-4103-80cf-407901cdb561",
    "hostUrl": "https://cdn.botpress.cloud/webchat/v0",
    "messagingUrl": "https://messaging.botpress.cloud",
    "clientId": "14ea4229-d163-4103-80cf-407901cdb561",
    "lazySocket": true,
    "botName": "Assitente Virtual",
    "avatarUrl": "https://cdn3.iconfinder.com/data/icons/artificial-intelligence-93/60/robot__message__robotics__artificial__intelligence-256.png",
   "frontendVersion": "v0",
    "useSessionStorage": true
});


}
export default function RootLayout({ children }) {
 

  return (
    <html lang="pt">
     <head>
      
      <Script src="https://cdn.botpress.cloud/webchat/v0/inject.js"
      onLoad={()=>{
        initBotpress();
      }}
      />
      

     </head>

      <body className={inter.className} suppressHydrationWarning={true}>
        <Navbar />
         {children}
        <Footer />
      </body>
    </html>
  );

  
}

