"use client";

import Navbar from "@/components/Navbar";
import "./globals.css";
import { Inter } from "next/font/google";
import Footer from "@/components/Footer";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Digital Soul",
  description: "Generated by next.js",
};

export default function RootLayout({ children }) {
 

  return (
    <html lang="en">
      <body className={inter.className} suppressHydrationWarning={true}>
        <Navbar />
         {children}
        <Footer />
      </body>
    </html>
  );
}
